// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fpvoqdMZc6Lryox1nYA0Zz26iJwSv5E',
    appId: '1:914562637113:web:d259caf86ae3bffed35ce8',
    messagingSenderId: '914562637113',
    projectId: 'evently-app-bbd93',
    authDomain: 'evently-app-bbd93.firebaseapp.com',
    storageBucket: 'evently-app-bbd93.firebasestorage.app',
    measurementId: 'G-XN25JFENN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCArKAnuef5X5q7CUnRNYQcTo5XbQVId7g',
    appId: '1:914562637113:android:bcb0bce6c0f98358d35ce8',
    messagingSenderId: '914562637113',
    projectId: 'evently-app-bbd93',
    storageBucket: 'evently-app-bbd93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPNfSXYTBKCblCz8w2AIyDQ_7xrhFmSE',
    appId: '1:914562637113:ios:4255d3f9d424c8a3d35ce8',
    messagingSenderId: '914562637113',
    projectId: 'evently-app-bbd93',
    storageBucket: 'evently-app-bbd93.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQPNfSXYTBKCblCz8w2AIyDQ_7xrhFmSE',
    appId: '1:914562637113:ios:4255d3f9d424c8a3d35ce8',
    messagingSenderId: '914562637113',
    projectId: 'evently-app-bbd93',
    storageBucket: 'evently-app-bbd93.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fpvoqdMZc6Lryox1nYA0Zz26iJwSv5E',
    appId: '1:914562637113:web:b53e8b2933695fb9d35ce8',
    messagingSenderId: '914562637113',
    projectId: 'evently-app-bbd93',
    authDomain: 'evently-app-bbd93.firebaseapp.com',
    storageBucket: 'evently-app-bbd93.firebasestorage.app',
    measurementId: 'G-S6B38LFECZ',
  );
}
